'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
import Image from 'next/image';

export default function AddProjectPage() {
  const [form, setForm] = useState({
    title: '',
    slug: '',
    description: '',
    projectMarkdown: '',
    tags: '',
    liveUrl: '',
    githubUrl: '',
    images: [] as Array<{ url: string; caption?: string; showOnProject?: boolean }>,
    featured: false,
    active: true,
  });
  const [uploading, setUploading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    (async () => {
      try {
        const me = await fetch('/api/auth/me', { credentials: 'same-origin' });
        if (!me.ok) router.push('/admin/login');
      } catch (err) {
        router.push('/admin/login');
      }
    })();
  }, []);

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('image', file);

    const res = await fetch('/api/upload', {
      method: 'POST',
      body: formData,
      credentials: 'same-origin',
    });

    if (res.ok) {
      const data = await res.json();
      setForm((f) => {
        const anyShown = (f.images || []).some((i) => i.showOnProject);
        return { ...f, images: [...(f.images || []), { url: data.url, showOnProject: !anyShown }] };
      });
    }
    setUploading(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const tags = form.tags ? form.tags.split(',').map(t => t.trim()).filter(Boolean) : [];
    // auto-generate slug and description if missing so backend validation passes
    const slug = form.slug && form.slug.trim() ? form.slug.trim() : (form.title ? form.title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') : `project-${Date.now()}`);
    const description = form.description && form.description.trim() ? form.description.trim() : 'No description provided.';

    const payload = { ...form, tags, slug, description };

    const res = await fetch('/api/projects', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'same-origin',
      body: JSON.stringify(payload),
    });
    const j = await res.json().catch(() => ({ success: false, message: 'Invalid response' }));
    if (j?.success) {
      // show lightweight feedback and navigate
      alert('Project added');
      router.push('/admin/projects');
    } else {
      alert(j?.message || 'Add failed');
    }
  };

  return (
    <div className="p-6">
      <h1 className="text-2xl mb-4">Add Project</h1>
      <form onSubmit={handleSubmit} className="space-y-4">
        <input
          type="text"
          placeholder="Title (recommended)"
          value={form.title}
          onChange={(e) => setForm({ ...form, title: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="text"
          placeholder="Slug (optional - autogenerated if left blank)"
          value={form.slug}
          onChange={(e) => setForm({ ...form, slug: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <textarea
          placeholder="Description (optional)"
          value={form.description}
          onChange={(e) => setForm({ ...form, description: e.target.value })}
          className="w-full p-2 border rounded"
          rows={6}
        />
        <label className="block mt-2 text-sm font-medium">Project Markdown (optional, supports Markdown)</label>
        <textarea
          placeholder="Project markdown (renders on public project page)"
          value={form.projectMarkdown}
          onChange={(e) => setForm({ ...form, projectMarkdown: e.target.value })}
          className="w-full p-2 border rounded"
          rows={8}
        />
        <input
          type="text"
          placeholder="Tags (comma separated)"
          value={form.tags}
          onChange={(e) => setForm({ ...form, tags: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="url"
          placeholder="Live URL"
          value={form.liveUrl}
          onChange={(e) => setForm({ ...form, liveUrl: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="url"
          placeholder="GitHub URL"
          value={form.githubUrl}
          onChange={(e) => setForm({ ...form, githubUrl: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="file"
          accept="image/*"
          onChange={handleImageUpload}
          className="w-full p-2 border rounded"
        />
        {uploading && <p>Uploading...</p>}
        {form.images && form.images[0]?.url && (
          <Image src={form.images[0].url} alt="Preview" width={128} height={128} className="w-32 h-32" />
        )}
        <div>
          <label className="inline-flex items-center gap-2">
            <input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />
            <span className="text-sm">Active</span>
          </label>
        </div>
        <label>
          <input
            type="checkbox"
            checked={form.featured}
            onChange={(e) => setForm({ ...form, featured: e.target.checked })}
          />
          Featured
        </label>
        <button type="submit" className="btn-accent px-4 py-2 rounded cursor-pointer">
          Add Project
        </button>
      </form>
    </div>
  );
}