'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
import Image from 'next/image';

import DropzoneFileUpload from '../../../components/ui/DropzoneFileUpload';

export default function AddCertificationPage() {
  const [form, setForm] = useState({
    title: '',
    slug: '',
    description: '',
    tags: '',
    link: '',
    image: '',
    pdf: '', // Add pdf state
    issuer: '',
    issueDate: '',
    expiryDate: '',
    credentialId: '',
    featured: false,
    active: true,
  });
  const [uploading, setUploading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    (async () => {
      try {
        const me = await fetch('/api/auth/me', { credentials: 'same-origin' });
        if (!me.ok) router.push('/admin/login');
      } catch (err) {
        router.push('/admin/login');
      }
    })();
  }, []);

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploading(true);
    const formData = new FormData();
    formData.append('image', file);

    const res = await fetch('/api/upload', {
      method: 'POST',
      body: formData,
      credentials: 'same-origin',
    });

    if (res.ok) {
      const data = await res.json();
      setForm((f) => ({ ...f, image: data.url }));
    }
    setUploading(false);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const tags = form.tags ? form.tags.split(',').map(t => t.trim()).filter(Boolean) : [];
    // auto-generate slug and description if missing so backend validation passes
    const slug = form.slug && form.slug.trim() ? form.slug.trim() : (form.title ? form.title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-') : `certification-${Date.now()}`);
    const description = form.description && form.description.trim() ? form.description.trim() : 'No description provided.';

    const payload = { ...form, tags, slug, description };

    const res = await fetch('/api/certifications', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'same-origin',
      body: JSON.stringify(payload),
    });
    const j = await res.json().catch(() => ({ success: false, message: 'Invalid response' }));
    if (j?.success) {
      // show lightweight feedback and navigate
      alert('Certification added');
      router.push('/admin/certifications');
    } else {
      alert(j?.message || 'Add failed');
    }
  };

  return (
    <div className="p-6">
      <h1 className="text-2xl mb-4">Add Certification</h1>
      <form onSubmit={handleSubmit} className="space-y-4">
        <input
          type="text"
          placeholder="Title (recommended)"
          value={form.title}
          onChange={(e) => setForm({ ...form, title: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="text"
          placeholder="Slug (optional - autogenerated if left blank)"
          value={form.slug}
          onChange={(e) => setForm({ ...form, slug: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <textarea
          placeholder="Description"
          value={form.description}
          onChange={(e) => setForm({ ...form, description: e.target.value })}
          className="w-full p-2 border rounded"
          rows={6}
        />
        <input
          type="text"
          placeholder="Tags (comma separated)"
          value={form.tags}
          onChange={(e) => setForm({ ...form, tags: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="url"
          placeholder="Link (optional)"
          value={form.link}
          onChange={(e) => setForm({ ...form, link: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="text"
          placeholder="Issuer"
          value={form.issuer}
          onChange={(e) => setForm({ ...form, issuer: e.target.value })}
          className="w-full p-2 border rounded"
          required
        />
        <input
          type="date"
          placeholder="Issue Date"
          value={form.issueDate}
          onChange={(e) => setForm({ ...form, issueDate: e.target.value })}
          className="w-full p-2 border rounded"
          required
        />
        <input
          type="date"
          placeholder="Expiry Date (optional)"
          value={form.expiryDate}
          onChange={(e) => setForm({ ...form, expiryDate: e.target.value })}
          className="w-full p-2 border rounded"
        />
        <input
          type="text"
          placeholder="Credential ID (optional)"
          value={form.credentialId}
          onChange={(e) => setForm({ ...form, credentialId: e.target.value })}
          className="w-full p-2 border rounded"
        />

        {/* PDF Upload */}
        <div>
          <label className="block text-sm font-medium mb-1">Upload Certificate PDF (Optional)</label>
          <DropzoneFileUpload
            onUploaded={(url) => setForm(f => ({ ...f, pdf: url }))}
            initialUrl={form.pdf}
          />
        </div>

        {/* Image Upload */}
        <div>
          <label className="block text-sm font-medium mb-1">Company/Issuer Logo or Cover Image</label>
          <input
            type="file"
            accept="image/*"
            onChange={handleImageUpload}
            className="w-full p-2 border rounded mb-2"
          />
          {uploading && <p>Uploading...</p>}
          {form.image && (
            <Image src={form.image} alt="Preview" width={128} height={128} className="w-32 h-32 object-cover rounded" />
          )}
        </div>

        <div>
          <label className="inline-flex items-center gap-2">
            <input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />
            <span className="text-sm">Active</span>
          </label>
        </div>
        <label>
          <input
            type="checkbox"
            checked={form.featured}
            onChange={(e) => setForm({ ...form, featured: e.target.checked })}
          />
          Featured
        </label>
        <button type="submit" className="btn-accent px-4 py-2 rounded cursor-pointer">
          Add Certification
        </button>
      </form>
    </div>
  );
}